#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
    then echo "This script must be run as root"
    exit 1
fi

docker pull linuxserver/transmission
docker pull linuxserver/sonarr

docker stop transmission sonarr
docker rm transmission sonarr

docker run \
    -d \
    --name="transmission" \
    --net="host" \
    --restart=always \
    -e PGID=1000 -e PUID=1000 \
    -e TZ="America/Toronto" \
    -v /srv/docker/transmission/config:/config \
    -v /srv/docker/transmission/watch:/watch \
    -v /media:/downloads \
    linuxserver/transmission

docker run \
    -d \
    --name="sonarr" \
    --net="host" \
    --restart=always \
    -e PUID=1000 -e PGID=1000 \
    -e TZ="America/Toronto" \
    -v /etc/localtime:/etc/localtime:ro \
    -v /srv/docker/sonarr/config:/config \
    -v /srv/docker/sonarr/tv:/tv \
    -v /media:/downloads \
    linuxserver/sonarr

docker system prune

systemctl restart qos
