#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
    then echo "This script must be run as root"
    exit 1
fi

source /srv/docker/docker.conf

docker pull linuxserver/transmission
docker pull linuxserver/sonarr
docker pull rednoah/filebot

docker stop transmission sonarr filebot
docker system prune -f

docker run \
    -d \
    --name="transmission" \
    --net="host" \
    --restart=always \
    -e PGID=1000 -e PUID=1000 \
    -e TZ="America/Toronto" \
    -v /srv/docker/transmission/config:/config \
    -v /srv/docker/transmission/watch:/watch \
    -v /media:/downloads \
    linuxserver/transmission

docker run \
    -d \
    --name="sonarr" \
    --net="host" \
    --restart=always \
    -e PUID=1000 -e PGID=1000 \
    -e TZ="America/Toronto" \
    -v /etc/localtime:/etc/localtime:ro \
    -v /srv/docker/sonarr/config:/config \
    -v /srv/docker/sonarr/tv:/tv \
    -v /media:/downloads \
    linuxserver/sonarr

docker create \
    --name="filebot" \
    --net="host" \
    -v /media:/media \
    -p 5452:5452 \
    -e FILEBOT_NODE_AUTH=BASIC \
    -e FILEBOT_NODE_AUTH_USER="$FILEBOT_USER" \
    -e FILEBOT_NODE_AUTH_PASS="$FILEBOT_PASS" \
    -p 5453:5453 \
    -v /etc/letsencrypt:/etc/letsencrypt:ro \
    -e FILEBOT_NODE_HTTPS=YES \
    -e FILEBOT_NODE_HTTPS_PORT=5453 \
    -e FILEBOT_NODE_HTTPS_KEY="$SSL_KEY" \
    -e FILEBOT_NODE_HTTPS_CRT="$SSL_CRT" \
    rednoah/filebot:node

echo '### Filebot Customizations  ###'
echo 'Series Format:'
echo -e 'TV/{n}/{n} - {s00e00} - {t}\n'
echo 'Anime Format:'
echo -e 'Anime/{n}/{n} - {s00e00} - {t}\n'
echo 'Run Program:'
echo -e "chmod -R a+rwX '{folder}/'"

systemctl restart qos
